repos:

-   repo: https://github.com/kynan/nbstripout
    rev: 0.8.2
    hooks:
    -   id: nbstripout

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-merge-conflict

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4', --preserve-quotes]
    -   id: pretty-format-toml
        args: [--autofix]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
    -   id: ruff-format
        args: [--config=pyproject.toml]
    -   id: ruff-check
        args: [--config=pyproject.toml, --fix, --unsafe-fixes, --output-format=concise, --quiet]


-   repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.2.0
    hooks:
    -   id: rm-unneeded-f-str

-   repo: https://github.com/numpy/numpydoc
    rev: v1.8.0
    hooks:
    -   id: numpydoc-validation
        exclude: '^(need-clean/)'

# -   repo: local
#     hooks:
#     -   id: mypy
#         name: mypy
#         entry: mypy
#         args: [--show-error-codes, --explicit-package-bases, --config-file=pyproject.toml]
#         language: system
#         types: [python]
#         require_serial: true
#         exclude: ^(sandbox|docs)/

# -   repo: local
#     hooks:
#     -   id: pytest
#         name: pytest
#         entry: pytest
#         args: [-W, "ignore::DeprecationWarning", -s]
#         language: system
#         types: [python]
#         require_serial: true
#         exclude: ^(sandbox|docs)/
